### ISSUE TITLE
cannot verify user on my main account

### ISSUE THREAD

**Issue by PeasIn** [Stefanuk12/RoProPatcher#17]
i tried to verify my user but failed, but my alternative account successfully verified its user.

1. Click on "verify My User"
2. See error

**Screenshots**
![image](https://user-images.githubusercontent.com/74363821/232958785-16aae0c1-5385-4f3e-8e34-aa59b708b9cc.png)
![Screenshot (10)](https://user-images.githubusercontent.com/74363821/232958814-2aa7b919-5754-4a0d-b828-754e6f57b148.png)

**Desktop (please complete the following information):**
 - OS: Windows 11 22H2
 - Browser: Chrome
 - Chrome Version: 112.0.5615.138
 - OS Version: 22H2

**Comment by Stefanuk12** [comment]
It's a RoPro issue. Also you're verified in the second image?

**Comment by PeasIn** [comment]
> It's a RoPro issue. Also you're verified in the second image?

yes, thats the issue.
