### ISSUE TITLE
cannot verify user and the normal ropro does not do this

### ISSUE THREAD

**Issue by pro11x11** [Stefanuk12/RoProPatcher#18]
**Describe the bug**
cannot verify user and the normal ropro does not do this
**To Reproduce**
1. Go to 'roblox.com/home'
2. Click on 'verify my user'

**Expected behavior**
the normal ropro does not do this
**Screenshots**
https://youtu.be/QYK4nN57JY4
![Capture d’écran 2023-06-11 164819](https://github.com/Stefanuk12/RoProPatcher/assets/110092289/02bff8df-495c-420e-8b53-296a1e1eaefd)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10 64bits ]
 - Browser [e.g. chrome]
 - Version [e.g. Version 114.0.5735.110 (Build officiel) (64 bits)
]
**Additional context**
for the browser with ropro not pached 
the version is microsoft edge Version 114.0.1823.43 (Version officielle) (64 bits)
and I tested without the other extensions and it didn't work

**Comment by Stefanuk12** [comment]
can't fix and won't fix.

more information: the verification endpoint does not go through the proxy - only things related to verifying your subscription
