### ISSUE TITLE
RoPro can't load after patching it.

### ISSUE THREAD

**Issue by NOTGTM** [Stefanuk12/RoProPatcher#20]
**Describe the bug**
RoPro extension unable to load after patching it on Opera GX

**To Reproduce**
1. Get RoPro
2. Patch it
3. Go into RoPro extension
4. See bug

**Expected behavior**
Get RoPro Rex

**Screenshots**
![image](https://github.com/Stefanuk12/RoProPatcher/assets/107492638/7f93a5f3-fc91-4050-af33-b53234328b0e)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Opera GX
 - Version of Opera GX: 99.0.4788.77
 - Version of RoPro: 1.5.9
 - Version of Patcher: 1.1.3

ROPRO LOADED BEFORE PATCH

**Comment by Stefanuk12** [comment]
deno.dev have finally caught on and I have reached my quota. you need to make your own proxy now or use darkhub's.

will make update soon...

**Comment by Stefanuk12** [comment]
I've updated the README to reflect this. I will update it to use darkhub's proxy soon...
