### ISSUE TITLE
Unknown Region

### ISSUE THREAD

**Issue by vTrustVlone** [Stefanuk12/RoProPatcher#26]
When I try changing the server region or use "Best Connection", It doesnt load or it just shows Unknown Region

**Comment by Stefanuk12** [comment]
phpsessid expired again or something, working on it

**Comment by vTrustVlone** [comment]
alright.

**Comment by doxxex** [comment]
btw good work man thanks for the efforts

**Comment by Stefanuk12** [comment]
they're taking too long to respond... does anyone else have a ropro sub they're willing to share? you cannot use the account you have it on tho

**Comment by vTrustVlone** [comment]
still not up but thanks for the efforts man, try finding someone who is willing to share it

**Comment by Stefanuk12** [comment]
updated the token...

**Comment by Stefanuk12** [comment]
seems to be working now, i will reopen whenever it goes down again
