### ISSUE TITLE
rolimon value and demand rating showing  as NaN or 0

### ISSUE THREAD

**Issue by synandburgerontop** [Stefanuk12/RoProPatcher#27]
![image](https://github.com/Stefanuk12/RoProPatcher/assets/116931372/6bad2397-fc05-4c16-8c3b-767e97a1369e)

**Comment by Stefanuk12** [comment]
was it working before?

**Comment by Ducky443747** [comment]
it was working for me a while ago at least

**Comment by Stefanuk12** [comment]
probably a ropro issue

**Comment by Stefanuk12** [comment]
This is happening because the current PHPSESSID is linked to a RoPro Plus subscription, not Rex.
