### ISSUE TITLE
confusion about the steps.

### ISSUE THREAD

**Issue by m0nnk3y** [Stefanuk12/RoProPatcher#3]
im confused what the steps mean, i went to the path: %appdata%\Mozilla\Firefox\Profiles, it says "followed by your profile name (the most recently modified folder) and finally into extensions." i see so many extension folders but dont know which one do go into.

**Comment by Stefanuk12** [comment]
You see many extension folders within your Profile folder? Could you please show your profile directory along with the contents of a few extension folders?

**Comment by Anexzs** [comment]
Also quite confused. Do I extract this folder and then set the directory as the extracted folder in extensions?
![image](https://user-images.githubusercontent.com/32688793/186271202-f4e58537-020f-4e71-889c-68f08e59e295.png)

**Comment by m0nnk3y** [comment]
> You see many extension folders within your Profile folder? Could you please show your profile directory along with the contents of a few extension folders?

![image](https://user-images.githubusercontent.com/89505551/186832956-8cc3bf8a-c54a-4688-a156-6bcb0da0dbb9.png)

**Comment by Stefanuk12** [comment]
Please follow the manual installation process that allows you to install extensions in Brave via developer mode. Even if you were to succeed with this, it would flag as corrupted. However, you need the one marked as release or the one most recently modified.
