### ISSUE TITLE
Unknown Region

### ISSUE THREAD

**Issue by Stefanuk12** [Stefanuk12/RoProPatcher#31]
# Why this happens

If this issue is open, it means that the server filters are not working at the moment. This is usually because the token got invalidated.

# What you can do to help

1. Wait patiently for a new token
2. Donate a months worth of a RoPro Rex subscription by contacting me on Discord after purchasing it

# Help, I'm having this issue but the issue is closed

Make sure that you're experiencing the unknown region across all servers. It's common to have many that say "Unknown Region" but then the there's one that does work. This is a RoPro fault.

If you have checked and sure it's not working, then you can either let me know on Discord or comment under this issue post.

# I want to donate my RoPro subscription, how do I do it?

1. Follow [this](https://github.com/Stefanuk12/RoProPatcher/tree/proxy#grabbing-your-own-phpsessid) tutorial on getting your PHPSESSID
2. Go to [this](https://github.com/Stefanuk12/RoProPatcher/blob/proxy/data.json) file
3. Press the pencil (edit) button and replace the current PHPSESSID there
4. Save your changes by committing them

By following this process, you will make a pull request which will allow me to add it easily.

**Comment by Miloiscute12** [comment]
new error Manifest version 2 is deprecated, and support will be removed in 2023. See https://developer.chrome.com/blog/mv2-transition/ for more details. its when i try to unpack the patch in opera and google

**Comment by builtbyvys** [comment]
Hey @Stefanuk12! I've purchased a pro subscription, and I'll be doing so for a while. If you'd like to get in contact, please dm me over at (https://discord.com/users/398304429788626946) or shoot me [an email](mailto:vys@tuta.io).

**Comment by Stefanuk12** [comment]
> Hey @Stefanuk12! I've purchased a pro subscription, and I'll be doing so for a while. If you'd like to get in contact, please dm me over at (https://discord.com/users/398304429788626946) or shoot me [an email](mailto:vys@tuta.io).

@builtbyvys I'm not able to add you through that link, what's your username?

**Comment by builtbyvys** [comment]
My username is "vyslix"

**Comment by Stefanuk12** [comment]
Fixed, will re-open if not working again.
