### ISSUE TITLE
Confused on RoPro Verification Token

### ISSUE THREAD

**Issue by fastvariable** [Stefanuk12/RoProPatcher#44]
**Is your feature request related to a problem? Please describe.**
Yes, I can not understand RoPro Verification Token
**Describe the solution you'd like**
Better Explanation
**Describe alternatives you've considered**
Video
**Additional context**
no

**Comment by Stefanuk12** [comment]
Don't worry about it, it's only used to track your playtime / to verify your account. If you still want this token, please explain what you're confused about and what you've tried.

**Comment by fastvariable** [comment]
I've tried the console and i pasted await getStorage("userVerification") and entered, I don't know what do next so i pasted {USERID: 'TOKEN'} and replaced with my ID and Token and after doing that nothing happened .

The token is my roblox cookie right?

can you tell me what do to i cant seem to understand the thing


(im using edge)

**Comment by Stefanuk12** [comment]
After running getStorage command, you should get a response with your token. The token there is not your Roblox token but your verification token.

May I ask why you want it?
