### ISSUE TITLE
I don't know how to get the token

### ISSUE THREAD

**Issue by muratiste** [Stefanuk12/RoProPatcher#45]
I can send a screenshot I can't send a video
I'm Using Google Windows 10
Version newest

When I type await getStorage("userVerification") nothing happens and I don't know how to get my token. Can you explain in detail and also will I be able to customize my profile and track my game time after doing this?
![image](https://github.com/Stefanuk12/RoProPatcher/assets/77173794/7d5b39fa-deae-41df-afcb-59bca0bdd38f)

**Comment by Stefanuk12** [comment]
Make sure you have verified yourself first. I believe it only tracks playtime.

**Comment by muratiste** [comment]
When I press the Verify My User Button I get this error:
![image](https://github.com/Stefanuk12/RoProPatcher/assets/77173794/aedff8a6-5a37-45ac-9568-e20c4837d5e9)

**Comment by Stefanuk12** [comment]
This is an issue on RoPro's end. Keep trying

**Comment by muratiste** [comment]
ok let me try some

**Comment by muratiste** [comment]
i pressed the button multiple times and i get this error:
![image](https://github.com/Stefanuk12/RoProPatcher/assets/77173794/9707d825-7096-440f-a418-11d586fce40d)
I closed and opened google, rewrote the await getStorage("userVerification") command again, pressed the button again, it didn't fix, I get the error in the picture

**Comment by muratiste** [comment]
![image](https://github.com/Stefanuk12/RoProPatcher/assets/77173794/294e02ba-932f-43f5-b2be-5ff0ae20bd41)
What's written in the json file:

**Comment by Stefanuk12** [comment]
Yeah this is a RoPro issue.

**Comment by muratiste** [comment]
I was just wondering what does the await getStorage("user Verification") command do?

**Comment by Stefanuk12** [comment]
It grabs the user verification token from the local storage for the extension.

**Comment by muratiste** [comment]
So there is no way to fix it?

**Comment by Stefanuk12** [comment]
Correct

**Comment by muratiste** [comment]
correct?

**Comment by jeremylpro** [comment]
bruh
