### ISSUE TITLE
Extention Error

### ISSUE THREAD

**Issue by Astrogragh** [Stefanuk12/RoProPatcher#47]
I'm not sure if this is serious or if you guys are already aware of this error, I just wanted to let you guys know.

For chrome if you go to [manage extention](chrome://extensions/) I would see the button Error next to Details and Remove which would show me an error "Manifest version 2 is deprecated, and support will be removed in 2023. See https://developer.chrome.com/blog/mv2-transition/ for more details."

![image](https://github.com/Stefanuk12/RoProPatcher/assets/84880137/71d35787-34c6-4ff5-84c6-81aaf6203146)

**Comment by Stefanuk12** [comment]
Yeah the issue is with RoPro, they haven't updated to v3 yet. For now, the warning can be ignored until v3 is enforced.

**Comment by NoodlesSoupEXE** [comment]
> Yeah the issue is with RoPro, they haven't updated to v3 yet. For now, the warning can be ignored until v3 is enforced.

Ok thanks I just wasn't sure if this was anything major.
