### ISSUE TITLE
please remove all the "verify things"

### ISSUE THREAD

**Issue by isacxx** [Stefanuk12/RoProPatcher#49]
**Is your feature request related to a problem? Please describe.**

Yes, It is very annoying to see the top games telling you to verify even though you can't,  many features are required to get verified from ropro.

**Describe the solution you'd like**

It would be nice if you have an option to disable anything that requires verifying to just get it out of the way.

**Describe alternatives you've considered**

just getting the free version of ropro

**Comment by isacxx** [comment]
i found out that you can trick the ropro patcher extension to thinking you are verified, just add the real ropro extension to the account you want to verify and verify (verify the free ropro) then remove the free ropro and you will be verified on ropatcher.

**Comment by Stefanuk12** [comment]
verification is not linked to the patcher at all
