### ISSUE TITLE
Macintosh support

### ISSUE THREAD

**Issue by boosy-313** [Stefanuk12/RoProPatcher#57]
To be honest, the only reason I would like this feature is for the region selector, and that's pretty much it. Was using RoQOL, but they recently changed it and I can no longer use it.

If you guys could suggest an alternative, or provide support for MacOS Sonoma, it would be greatly appreciated.

P.S. I would support the original creators, however, my parents are in a pretty tight spot right now. 

Cheers!

**Comment by Stefanuk12** [comment]
The patcher itself should be able to compile to MacOS. The extension itself, I'm not sure.

**Comment by boosy-313** [comment]
Nah, it doesn't work. The patcher uses a .exe file format which is not Mac compatible.

**Comment by Stefanuk12** [comment]
No but you can compile the source code yourself to use with MacOS is what I'm saying. You can find tutorials online on how to compile Rust code.

**Comment by boosy-313** [comment]
Thanks for the help.

**Comment by boosy-313** [comment]
I'll fiddle around and see if I can get it to work, will update you on it.

**Comment by boosy-313** [comment]
A bit too complicated for me, but that's okay. Crossing my fingers that a more experienced macOS user picks up on this and uploads a tutorial or something
