### ISSUE TITLE
[BUG] Can't save themes

### ISSUE THREAD

**Issue by Nyxlanders** [Stefanuk12/RoProPatcher#58]
**Describe the bug**
Can't save the theme in the "Themes" page of RoPro extension, whenever I try I receive the message: "Error: Unknown error, please try again later.".

**To Reproduce**
1. Click on "Themes" in the Roblox sidebar.
2. Click on any theme.
3. Click on "Save Theme"
4. Error message appear.
5. See that theme doesn't apply anywhere.

**Expected behavior**
I expect to my theme to be applied and fully working.

**Screenshots**
![image](https://github.com/Stefanuk12/RoProPatcher/assets/66521547/70bab7cf-2da9-4a88-b1f9-7393c156726c)
Error message.

![image](https://github.com/Stefanuk12/RoProPatcher/assets/66521547/4ead6a51-dade-4897-aeef-39a117c55b2e)
Removing theme works only in Themes page.

![image](https://github.com/Stefanuk12/RoProPatcher/assets/66521547/d6fc6cf7-aa4b-470a-a54a-e223d41239b0)
Old theme from older versions covering new theme.

**Desktop (please complete the following information):**
 - OS: [Windows 11]
 - Browser [Chrome]
 - Version [122.0.6261.112 (Official version) 64 bits]

**Additional context**
Apparently, my old theme from older versions of RoPro is showing and covering the old theme when I first enter the Themes page (in the third screenshot) and "Remove Theme" sorts of work...? (Second screenshot).

**Comment by Stefanuk12** [comment]
I'm not sure about this one. The patcher doesn't change anything relating to themes but animated themes will not work as outlined in #28

**Comment by Nyxlyzers** [comment]
> I'm not sure about this one. The patcher doesn't change anything relating to themes but animated themes will not work as outlined in #28

Yes, but I can't use any themes. I'm not sure if it's maybe a bug relating my RoPro account specific, because I'm stuck with my old theme from previous updates.

**Comment by SuppliedOrange** [comment]
You can't do this because themes handled on ropro's servers. You'd have to change their code to locally save your theme. Even then, others won't be able to see your theme.
