### ISSUE TITLE
rat and malware

### ISSUE THREAD

**Issue by denveel** [Stefanuk12/RoProPatcher#59]
https://www.virustotal.com/gui/file/46f5c8193c48a88e3852a85a3a6a22a178f593b62e9ad955f3fbc5f5bfbccdab/details look

**Comment by SillyVentilator** [comment]
its  false detect , you can check any other exe file and with chance 50% its will be have it

**Comment by Stefanuk12** [comment]
It's also open sourced so you can compile it yourself.
