### ISSUE TITLE
false positive?

### ISSUE THREAD

**Issue by toxicfox2491** [Stefanuk12/RoProPatcher#6]
Id just like to point out having an exe file modify an extension is sus and not to mention virustotal  gave it a 5

**Comment by Stefanuk12** [comment]
> Id just like to point out having an exe file modify an extension is sus and not to mention virustotal  gave it a 5
> 
> 

This has been raised as an issue before. It's open source for a reason, you're more than welcome to compile the code yourself and you would see that you would get the same false positives. The reason it's an exe is because I wanted to get some experience using Rust.

**Comment by AltariasMainAccount** [comment]
The reason why this is flagged as a false positive is because it tries to access the browser data of the selected browser/path.
Based on my research of opening the compiled project myself and opening the one I downloaded from here there seems to be no differences. However, it does not seem to be working on Windows 11 (64x) (unless I have done something wrong)

**Comment by Stefanuk12** [comment]
> The reason why this is flagged as a false positive is because it tries to access the browser data of the selected browser/path.
> 
> Based on my research of opening the compiled project myself and opening the one I downloaded from here there seems to be no differences. However, it does not seem to be working on Windows 11 (64x) (unless I have done something wrong)
> 
> 
> 
> Slight edit, the antivirus engines that *have* infact detected it are objectively kind of bad.
> 
> ![image](https://user-images.githubusercontent.com/31167322/204353548-c36de632-c71c-49de-9df9-a5bb089950e2.png)
> 
> 

Yeah people have been reporting it not working, I currently don't have the time to look into it but hopefully I will get to it in due time

**Comment by toxicfox2491** [comment]
> > Id just like to point out having an exe file modify an extension is sus and not to mention virustotal  gave it a 5
> 
> This has been raised as an issue before. It's open source for a reason, you're more than welcome to compile the code yourself and you would see that you would get the same false positives. The reason it's an exe is because I wanted to get some experience using Rust.

Ive put both yours and the original through virus total bruv and yours is way worse,

**Comment by toxicfox2491** [comment]
OOP- sorry I thought this was something else sorry about that
