### ISSUE TITLE
Your proxies are dead. RoPro have also changed their methods.

### ISSUE THREAD

**Issue by SuppliedOrange** [Stefanuk12/RoProPatcher#62]
They have an activateKey function in `RoPro/js/page/options.js` with the API link hardcoded. Proxies were kind of a far-fetch to begin with.

**Comment by Stefanuk12** [comment]
Feel free to modify the patcher to work properly then create a PR. I don't have the time at the moment to work on this.

**Comment by SuppliedOrange** [comment]
Hi, I decided to take the easy route and change the function to a basic `if (true) subscription is valid`. I'm too lazy to make or maintain a proxy.

**Comment by Stefanuk12** [comment]
> I'm too lazy to make or maintain a proxy. 

You don't need to make your own proxy or maintain it. There's a separate branch that already has the proxy done.

**Comment by blueiicey** [comment]
It seems to be working just fine for me.

**Comment by Slasher098** [comment]
> > I'm too lazy to make or maintain a proxy.
> 
> You don't need to make your own proxy or maintain it. There's a separate branch that already has the proxy done.

Hey I just stumble across this, I used the GUI and it downloaded properly, the only thing is things like server region and uptime say UNKNOWN, is this an issue with proxies I am able to fix?

**Comment by Stefanuk12** [comment]
It could be that. It also could be that the account that was being used no longer has rex

**Comment by johnhub154** [comment]
is this going to be fixed soon?

**Comment by Stefanuk12** [comment]
Not any time soon by me, I don't have the time nor dedication to maintain this. The only reason I haven't archived is to allow the possibility for someone else to fix.
