### ISSUE TITLE
new update or smth

### ISSUE THREAD

**Issue by Night-boxx** [Stefanuk12/RoProPatcher#64]
**Describe the bug**
the devs prbl fixed the patcher version and it doesnt show up and doesnt connect to the network + the videos dont work and the text idk

**Expected behavior**
it doesnt load the new extension

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: [PC]
 - Browser [Opera GX]
 - v1.3

**Comment by Stefanuk12** [comment]
Duplicate of #62.
