### ISSUE TITLE
Im not too sure if this is RoPro's fault or the patcher but server filters (premium) wont work

### ISSUE THREAD

**Issue by roblosus** [Stefanuk12/RoProPatcher#8]
All of the server filters in the premium category do not work as intended.

1. Go to any game
2. Click on the Servers button
3. Scroll down to the filters and click any of the premium ones

This was working as intended just yesterday

**Comment by Stefanuk12** [comment]
it only works as certain times atm. specifically, when i'm
online. will look into it later

**Comment by roblosus** [comment]
It works now
